services:
  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: jobai-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus-local.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:11.3.0
    container_name: jobai-grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1542441175896555540/bOwGcokaF2cujDuz7VWRIxwiLqVxg8jNmqDYpEMPiDhITgvh15QT84Yljm1_ZptJyO5j
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

volumes:
  grafana_data:
